### ISSUE TITLE
Tp ended

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/4a-isi3-tp1-2016-2017-groupe-2-gory-prieurdrevon#1]
* ⚠️ le markdown c'est pas encore ça, essayer la coloration syntaxique => pensez à mes yeux. Et les ###### vous avez loupé un truc 😉 

* 👍 pour les patterns

* 💡 supprimer les getter et setter inutiles

* ⚠️ utiliser StringBuilder c'est pas pour faire des " "+" " dedans => soit décomposer l'append soit utiliter String.format()

**Comment by agory** [comment]
Changement effectué

Merci pour les retours 👍
